#! /usr/bin/python

# @file
#  This file is part of gambit2vtk
#
#  For conditions of distribution and use, please see the copyright
#  notice in the file 'COPYING' at the root directory of this package
#  and the copyright notice at https://github.com/TUM-I5/gambit2vtk
# 
# @copyright 2012 Technische Universitaet Muenchen
# @author Sebastian Rettenberger <rettenbs@in.tum.de>

import os

Import('env')

env.src_files.append(Glob('*.cpp'))

Export('env')